### ISSUE TITLE
Trouble with 3.x

### ISSUE THREAD

**Issue by zotopteam** [svenluijten/flex-env#18]
when i composer update with：

{
    "require-dev": {
        "sven/flex-env": "^3.0"
    }
}

Then：

  Problem 1
    - Installation request for sven/flex-env ^3.0 -> satisfiable by sven/flex-env[3.0.x-dev].
    - Removal request for sven/flex-env == 3.0.9999999.9999999-dev

Change it to: "sven/flex-env": "3.0.x-dev", composer update ok ,but when i use: php artisan env:list

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Sven\FlexEnv\Env' not found

with the Laravel 5.5

**Comment by svenluijten** [comment]
3.x isn't out yet: https://github.com/svenluijten/flex-env/releases. However, just doing `composer require sven/flex-env` should work as before, even on 5.5.

Let me know!

**Comment by zotopteam** [comment]
Thanks
