### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by Pezhvak** [svenluijten/flex-env#53]
Hi, i just needed this for my project, but it's outdated, i would like to be a member to help you out if you will

**Comment by svenluijten** [comment]
Not sure what you're asking here exactly? Nevertheless, your PR (#52) is appreciated! 😄

**Comment by Pezhvak** [comment]
Never mind, i thought you have abandoned the repo, now that you're active, i can just create pull requests. thanks ^_^
